namespace ArtfulAdventures.Data.Models.Enums;

public enum HashTagType
{
    Abstract,
    Anatomy,
    Animals_Wildlife,
    Anime_Manga,
    Automotive,
    Architectural_Design,
    Art,
    Artist,
    Artwork,
    Character_Design,
    Comic,
    Creative,
    Drawing,
    Digital_Аrt,
    Digital_Painting,
    Digital_Drawing,
    Digital_Illustration,
    Digital_Portrait,
    Digital_Sketching,
    Environmental_Design,
    Fan_Art,
    Fantasy,
    Game_Art,
    Graffiti,
    Illustration,
    Mechanical_Design,
    Painting,
    Pixel_Art,
    Portrait,
    Props,
    Realism,
    Science_Fiction,
    Sketch,
    Street_Art,
    Vector_Art,
    Water_Color,
    Weapons,
    Unreal_Engine
}

